### ISSUE TITLE
Snapshot with embed Youtube

### ISSUE THREAD

**Issue by thientran1996** [Codecsocean/mediaelement-snapshot#1]
Hi there
Thank you for making this feature snapshot
I'm having a problem, when I snapshot with embed youtube, I just get a black image and there is an error like this
![image](https://user-images.githubusercontent.com/20870182/116207463-1b38a080-a76a-11eb-8b6d-6c4c9b95fd14.png)

I think it's because when embedding a video in Youtube, the content is displayed using an iframe

**Comment by Qoraiche** [comment]
Hi,
You welcome. Thanks for reporting, but I really don't have any plans to support iframe embed at the moment, feel free to submit a PR
